<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Aleksei Tcelishchev @casualuser
 * Date: 5/25/12
 * Time: 5:37 PM
 */

$urls = array(
    'forums.mozillazine.org',
    'community.elgg.org', // matching by separate 'elggrelease' tag
    'blog.s9y.org',
    'demo.avactis.com',
    'www.joomla.org',
    'www.vbulletin.com/forum',
    'wordpress.org/news',
    'xoops.org',
    'eurotux.com',
    'mediawiki.org',
    'cmsmadesimple.org',
    'silverstripe.com',
    'movabletype.org',
    'dream4.de',
    'bbpress.org/forums',
    'dokuwiki.org',
    'typo3.org',
    'phpnuke.org',
    'dotnetnuke.com',
    'sitefinity.com',
    'webgui.org',
    'ez.no',
    'bigace.de',
    'everything.typepad.com',
    'blogsofnote.blogspot.com',
    'demo-store.prestashop.com',
    'sharepoint.microsoft.com',
    'jalios.com',
    'demo.opensourcecms.com/zencart',
    'wpml.org',
    'pivotx.net',
    'openacs.org',
    'concrete5.org',
    'webnode.com',
    'get-simple.info',
    'dle-news.ru',
    'csphere.eu',
    'prototypejs.org',
    'ubercartdemo.com',
    'trymodx.com',
    'mootools.net',
    'dojotoolkit.org',
    'script.aculo.us',
    'disqus.com/explore',
    'vcitawibiya.blogspot.com',
    'google.com/recaptcha/demo/ajax',
    'shamwana.co.uk/demo/user',
    'zenphoto.org',
    'gallery.menalto.com/gallery/demosites',
    'xenforo.com',
    'gomockingbird.com/mockingbird',
    'audio.demo.volusion.com',
    'addthis.com',
    'thedroiddemos.com',
    'weebly.com',
    'twitter.github.com/bootstrap',
    'jeremyheintz.jigsy.com',
    'www.thedrive.coop'
);